ignite:
    igniteInstanceName: properties-instance-name
    communicationSpi:
        localPort: 5555
    dataStorageConfiguration:
        defaultDataRegionConfiguration:
            initialSize: 10485760 #10MB
        dataRegionConfigurations[0]:
            name: my-dataregion
            initialSize: 104857600 #100MB

